// import { Geist, Geist_Mono, Poppins } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar";
// import Footer from "../components/Footer";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-poppins",
// });
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "NAMSTEHIND",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} h-full antialiased`}
//     >
//       <body className="bg-gray-50">
        

//          <Navbar />  
    
      
//     {children}
  
//         <Footer />
//         </body>
//     </html>
//   );
// }


import localFont from "next/font/local";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const myCustomFont = localFont({
  src: [{ path: '../fonts/AbrilFatface-Regular.otf', weight: '400', style: 'normal' },
    { path: '../fonts/PlayfairDisplay-Black.otf', weight: '700', style: 'normal' },
    { path: '../fonts/PlayfairDisplay-Regular.otf', weight: '700', style: 'normal' },
  
  ] ,
  variable: "--font-custom",    
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// --- SEO Friendly Metadata ---
export const metadata = {
  title: {
    default: "Namaste Hind | Premium Travel Agency for Spiritual & Adventure Tours",
    template: "%s | Namaste Hind",
  },
  description: "Namaste Hind offers the best travel packages for Char Dham Yatra, Manali, Ladakh, Spiti, and Kashmir. Book your dream adventure today with ByteWings Technology support.",
  keywords: ["Travel Agency", "Char Dham Yatra", "Kashmir Tour", "Ladakh Trip", "Spiti Valley", "Manali Packages", "Namaste Hind"],
  authors: [{ name: "Jay Pawar" }],
  creator: "ByteWings Technology",
  icons: {
    icon: "/image/namastehindLogo.jpeg", // Aapka logo file public folder mein hona chahiye
    apple: "/logo.png",
  },
  openGraph: {
    title: "Namaste Hind - Explore India with Us",
    description: "Book spiritual and adventure tours across India. Reliable, safe, and premium travel experiences.",
    url: "https://namastehind.com",
    siteName: "Namaste Hind",
    images: [
      {
        url: "/image/namastehindLogo.jpeg", // Link share hone par jo image dikhegi
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_IN",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${myCustomFont.variable} h-full antialiased`}
    >
      {/* Search Engine Optimization ke liye viewport aur theme color */}
      <head>
        <meta name="theme-color" content="#dc2626" />
      </head>
      <body className="bg-gray-50 font-poppins">
        <Navbar />
        <main className="min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}